config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  resources :themes do
    resources :todos
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/theme.rb
class Theme < ApplicationRecord
    has_many :todo 
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :theme , class_name: "Theme", foreign_key: "theme_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:title_list, :status_theme, :type_list)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController


  # GET /todos or /todos.json
  def index
    
    @theme= Theme.find(params[:theme_id])
    @todos =@theme.todos

  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new

  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title_tasks, :description, :complete, :status_task, :theme_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "base", "module","leyout", "theme", "reset", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/themes/_form.html.erb
<div class="container-list .m-flex">  
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title_list, style: "display: block" %>
    <%= form.text_field :title_list %>
  </div>

  <div>
    <%= form.label :status_theme, style: "display: block" %>
    <%= form.text_field :status_theme %>
  </div>

  <div>
    <%= form.label :type_list, style: "display: block" %>
    <%= form.text_field :type_list %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Title list:</strong>
    <%= theme.title_list %>
  </p>

  <p>
    <strong>Status theme:</strong>
    <%= theme.status_theme %>
  </p>

  <p>
    <strong>Type list:</strong>
    <%= theme.type_list %>
  </p>

</div>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<div class="container-list .m-flex"> 
  <h1> Listas de tarefas</h1>
  <div class="content-list" >
    <p style="color: green"><%= notice %></p>
    <%= link_to "New theme", new_theme_path %>
      <div class="content-themes m-flex">
        <div class="car-list">
          <% @themes.each do |theme| %>
          <%= render theme %>
          <p>
            <%= link_to "Show this theme", theme %>
          </p>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/themes/new.html.erb
<div class="container-list .m-flex">    
  <div class="content-themes m-flex n-new-t">
    <h1>New theme</h1>

    <%= render "form", theme: @theme %>

    <br>

    <div>
      <%= link_to "Back to themes", themes_path %>
    </div>


  </div>
</div>

app/views/themes/show.html.erb
<div class="container-list "> 
  <div class="content-list" >
    <p style="color: green"><%= notice %></p>
    <div class="m-flex">
        <%= render @theme%>
        <%= link_to "Editar", edit_theme_path(@theme) %> |
        <%= link_to "Retornar", themes_path %>
        <%= link_to "New", new_theme_path %>
        <%= button_to "Excluir", @theme, method: :delete %>
    </div>
    <div class="content-themes m-flex">
      <%= link_to theme_todos_path(@theme)  %>
      <%= link_to 'Nova tarefa',  new_theme_todo_path(@theme)%>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<h1>Tarefas dessa lista</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <p>
        <%= todo.title_tasks%>
        <%= todo.description%>
        <%= todo.complete%>
        <%= todo.status_task%>
    </p>
  <% end %>

</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>

</div>